/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './about.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './about.component';
const styles_AboutComponent:any[] = [i0.styles];
export const RenderType_AboutComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_AboutComponent,data:{}});
export function View_AboutComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(-1,(null as any),['\n  about works!\n'])),(_l()(),i1.ɵted(-1,(null as any),
      ['\n']))],(null as any),(null as any));
}
export function View_AboutComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-about',
      ([] as any[]),(null as any),(null as any),(null as any),View_AboutComponent_0,
      RenderType_AboutComponent)),i1.ɵdid(1,114688,(null as any),0,i2.AboutComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const AboutComponentNgFactory:i1.ComponentFactory<i2.AboutComponent> = i1.ɵccf('app-about',
    i2.AboutComponent,View_AboutComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvdHVhbm0vRG9jdW1lbnRzL0NvZGUgV2l0aCBNb3NoL0FuZ3VsYXIvZGVwbG95LWRlbW8vc3JjL2FwcC9hYm91dC9hYm91dC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvdHVhbm0vRG9jdW1lbnRzL0NvZGUgV2l0aCBNb3NoL0FuZ3VsYXIvZGVwbG95LWRlbW8vc3JjL2FwcC9hYm91dC9hYm91dC5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy90dWFubS9Eb2N1bWVudHMvQ29kZSBXaXRoIE1vc2gvQW5ndWxhci9kZXBsb3ktZGVtby9zcmMvYXBwL2Fib3V0L2Fib3V0LmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvdHVhbm0vRG9jdW1lbnRzL0NvZGUgV2l0aCBNb3NoL0FuZ3VsYXIvZGVwbG95LWRlbW8vc3JjL2FwcC9hYm91dC9hYm91dC5jb21wb25lbnQudHMuQWJvdXRDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8cD5cbiAgYWJvdXQgd29ya3MhXG48L3A+XG4iLCI8YXBwLWFib3V0PjwvYXBwLWFib3V0PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBLHdFQUFHO2FBQUEsMkNBRUM7TUFBQTs7O29CQ0ZKO01BQUE7K0JBQUEsVUFBQTtNQUFBO0lBQUE7Ozs7In0=
