/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.media[_ngcontent-%COMP%] { \n    margin-bottom: 30px;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvdHVhbm0vRG9jdW1lbnRzL0NvZGUgV2l0aCBNb3NoL0FuZ3VsYXIvZGVwbG95LWRlbW8vc3JjL2FwcC9naXRodWItZm9sbG93ZXJzL2dpdGh1Yi1mb2xsb3dlcnMuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy90dWFubS9Eb2N1bWVudHMvQ29kZSBXaXRoIE1vc2gvQW5ndWxhci9kZXBsb3ktZGVtby9zcmMvYXBwL2dpdGh1Yi1mb2xsb3dlcnMvZ2l0aHViLWZvbGxvd2Vycy5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
